version: "3.8"
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=laravel_admin_test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
